### ISSUE TITLE
require rake

### ISSUE THREAD

**Issue by jcoyne** [cbeer/capistrano-one_time_key#5]
Rake is never required prior to loading the rake task.
```
/Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-one_time_key-0.1.0/lib/capistrano/tasks/one_time_key.rake:1:in `<main>': undefined method `namespace' for main:Object (NoMethodError)
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:281:in `block in load'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:281:in `load'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-one_time_key-0.1.0/lib/capistrano/one_time_key.rb:63:in `<main>'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dlss-capistrano-3.4.1/lib/dlss/capistrano.rb:1:in `<main>'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:95:in `rescue in block in require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `each'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `require'
	from /Users/jcoyne85/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/lib/bundler.rb:114:in `require'
	from /Users/jcoyne85/workspace/sul-dlss-labs/workflow-server-rails/config/application.rb:18:in `<top (required)>'
```

**Comment by jcoyne** [comment]
Fixed by switching `  gem 'dlss-capistrano'` to `  gem 'dlss-capistrano', require: false` in the `Gemfile`
